### PR TITLE
enable grpc server reflection

### PR DESCRIPTION
**Pull request by jdpedrie**
This PR adds support for server reflection, enabling the use of tools like [grpcui](https://github.com/fullstorydev/grpcui).

### CODE REVIEW

**Comment by jnioche** [comment]
Thanks @jdpedrie 
Any drawbacks in using it? I assume this won't affect performance in any way

**Comment by jdpedrie** [comment]
Not according to this [stackoverflow answer](https://stackoverflow.com/questions/75052916/performance-security-impact-of-enabling-grpc-server-reflection). I would imagine the service would be deployed either for testing/development, or in an internal environment, but it might still make sense to place it behind a config flag.

**Comment by jnioche** [comment]
> but it might still make sense to place it behind a config flag.

+1

**Comment by jdpedrie** [comment]
Done in the latest commit.

**Comment by jnioche** [comment]
thanks @jdpedrie

**Pull request merged**
