### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by MattiSG**
Thanks for contributing to URL Frontier, your efforts are appreciated!

Developer Certificate of Origin
===============================

By contributing to URL Frontier, you accept and agree to the following terms and conditions (the *Developer Certificate of Origin*) for your present and future contributions submitted to URL Frontier. 
Please refer to the *Developer Certificate of Origin* section in [`CONTRIBUTING.md`](CONTRIBUTING.md) for details.

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

Before opening a PR, please check that: 

* You've squashed your commits into a single one
* You've described what the PR does or at least point to a related issue
* You've signed-ff your commits with 'git commit -s'

Thanks!

### CODE REVIEW

**Comment by jnioche** [comment]
hi @MattiSG 

Thanks for the PR. 
The keys are definitely not based on the top level domain (e.g. .com) but on the paid one (e.g. digitalpebble.com). Your other suggestions are good.
If you commit a change, can you please sign it so that it passes the DCO? Thanks

**Comment by MattiSG** [comment]
Hi @jnioche and thanks for your quick reply  :)

To be honest, the time and energy it will take me to clone the repo locally, set up a signing key, push, update my PR, is just not worth it for me for a handful of typos in a README that I fixed as a courtesy when reading through the text. Feel free to just copy-paste what is relevant to you, update the doc and close this PR —or credit me with `Co-Authored-By: Matti Schneider <gh@mattischneider.fr>` in the commit body. Thank you for your understanding!

> the paid one

I was quite confused by that name. I would then suggest using simply “domain name” 🙂

**Comment by MattiSG** [comment]
Hi @jnioche and thanks for your quick reply  :)

To be honest, the time and energy it will take me to clone the repo locally, set up a signing key, push, update my PR, is just not worth it for me for a handful of typos in a README that I fixed as a courtesy when reading through the text. Feel free to just copy-paste what is relevant to you, update the doc and close this PR —or credit me with `Co-Authored-By: Matti Schneider <gh@mattischneider.fr>` in the commit body. Thank you for your understanding!

> the paid one

I was quite confused by that name. I would then suggest using simply “domain name” 🙂

**Comment by jnioche** [comment]
https://github.com/crawler-commons/url-frontier/commit/78b7be124a5e6243d39294c4b65cd09061b5b412

Thanks @MattiSG

**Comment by MattiSG** [comment]
> you shouldn't need to set up a signing key for a DCO though, just add '-s' to the commit command

The main friction point for me was having to switch from GitHub online edition to local clone and commands 🙂

Thanks for the credit!

**Pull request closed without merging**
